[tool.poetry]
name = "Buienalarm"
version = "0.1.0"
description = "Buienalarm Nederland."
authors = ["HiDiHo <hidiho@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
homeassistant = "^2024.11.1"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
black = "^23.9.1"
pylint = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
