[tool.poetry]
name = "Buienalarm"
version = "0.1.0"
description = "Buienalarm Nederland."
authors = ["HiDiHo <hidiho@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "custom_components/buienalarm" }
]

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
homeassistant = "^2025.3.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
black = "^25.1.0"
pylint = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
