[tool.poetry]
name = "Buienalarm"
version = "0.1.0"
description = "Buienalarm Nederland."
authors = ["HiDiHo <hidiho@gmail.com>"]
license = "MIT"              # Choose a license (MIT, Apache-2.0, etc.)
readme = "README.md"         # Path to your README file

[tool.poetry.dependencies]
python = "^3.12"            # Specify the Python version

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"          # Add development dependencies as needed

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
